name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint_and_test:
    name: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: make ci